Implementing the simple linear regression with custom class


In [1]:
import pandas as pd

In [2]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [4]:
class CustomLinearRegresssion:
    def __init__(self):
        self.m = None
        self.b = None
    def fit(self,X_train,y_train):
      num = 0
      den = 0
      for i in range(X_train.shape[0]):
        num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
        den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))

      self.m = num/den
      self.b = y_train.mean() - (self.m * X_train.mean())
    def predict(self,X_test):
      return self.m * X_test + self.b




In [3]:
pd.read_csv("placements.csv")

,IQ,CGPA
0,95,6.5
1,100,7.0
2,105,7.2
3,110,7.8
4,115,8.0
5,120,8.3
6,125,8.7
7,130,9.0
8,98,6.8
9,108,7.5


In [5]:
df = pd.DataFrame(pd.read_csv("placements.csv"))


In [10]:
X = df.iloc[:, 0].values
y= df.iloc[:, 1].values

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2 , random_state=2)


In [15]:
lr = CustomLinearRegresssion()



In [16]:
lr.fit(X_train,y_train)


In [21]:
print(X_test,y_test)

[128 115 120] [8.9 8.  8.3]


In [18]:
print(lr.predict(X_test))

[8.90634731 7.99596731 8.34611346]


**Implementing the custom Multiple Linear Regression with custom class**

In [23]:
from sklearn.datasets import load_diabetes


In [25]:
X, y = load_diabetes(return_X_y= True)

In [26]:
X.shape

(442, 10)

In [31]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [32]:
model.predict(X_test)

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [34]:
from sklearn.metrics import r2_score

In [35]:
r2_score(y_test,model.predict(X_test))

0.4399338661568968

In [37]:
model.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [38]:
model.intercept_

np.float64(151.88331005254167)

Now making our own multiple linear regression class


In [44]:
class CustomMultipleLinearRegression:
  def __init__(self):
    self.coef_ = None
    self.intercept_ = None
  def fit(self,X_train,y_train):
    X_train = np.insert(X_train,0,1,axis=1)
    betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
    self.intercept_ = betas[0]
    self.coef_ = betas[1:]
  def predict(self,X_test):
    y_pred = np.dot(X_test,self.coef_) + self.intercept_
    return y_pred

In [43]:
lr = CustomMultipleLinearRegression()
lr.fit(X_train, y_train)
prediction = lr.predict(X_test)
print(prediction)


[154.1213881  204.81835118 124.93755353 106.08950893 258.5348576
 256.3310074  118.75087616 119.52440696 101.50816735 190.54048661
 141.70656811 172.51883961 174.33861649 134.80942706 294.13994537
  94.11798038 211.97059795 156.49579378 134.21000428 119.62664644
 148.87842251 165.00873409 151.10021038 176.04063756 133.27769647
 221.29555392 197.17324941  96.1577688   50.26012711 230.48580317
 242.06073866 114.11129218  67.07532417  94.52943825 201.21415375
 167.05136201 159.881268   192.78746659 114.49551325 233.48234551
 140.82563045 121.0680409  192.27480772 191.12738845 179.16865788
 148.34935601 163.47414622 276.81647884 100.17926432 164.10555298
 255.80762189 136.9466204  152.37503699 107.92237882 194.21924678
  77.34670792 118.50482479  68.38335763 154.29258529 162.48840259
 168.36788326 156.87790322  97.14191797 238.1671215  145.46179904
 117.65702433 168.88784311 198.38683887 118.24053714 124.64552812
 223.17700368 200.63012386 129.54414666 158.1584765  154.332565
 114.47070769